In [1]:
import pandas as pd
import numpy as np

In [2]:
col_names = ["Year", "Day", "Hour", "B_Mag", "Bz", "Density", "Speed", "Kp_Index", "Sunspots"]
df = pd.read_csv('omni_daily_24years.csv', delim_whitespace=True, names=col_names, comment='#')

C:\Users\Harshad koli\AppData\Local\Temp\ipykernel_22548\2935508813.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('omni_daily_24years.csv', delim_whitespace=True, names=col_names, comment='#')

In [3]:
df.head(10)

   Year  Day  Hour  B_Mag   Bz  Density  Speed  Kp_Index  Sunspots
0  2000    1     0    6.5 -0.0      2.0  721.0        40        71
1  2000    2     0    5.1  0.4      2.0  679.0        30        75
2  2000    3     0    4.9 -0.1      2.3  588.0        27        80
3  2000    4     0    5.8 -0.6      2.3  577.0        27        95
4  2000    5     0    6.0 -1.6      2.3  521.0        33       108
5  2000    6     0    6.9 -0.0      4.0  533.0        33       126
6  2000    7     0    4.5 -0.1      2.5  522.0        23       126
7  2000    8     0    3.8  0.1      2.3  439.0        13       111
8  2000    9     0    3.6  0.0      5.3  357.0         7       112
9  2000   10     0    6.8 -1.0     11.2  334.0        17        96

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9132 entries, 0 to 9131
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      9132 non-null   int64
 1   Day       9132 non-null   int64
 2   Hour      9132 non-null   int64
 3   B_Mag     9132 non-null   float64
 4   Bz        9132 non-null   float64
 5   Density   9132 non-null   float64
 6   Speed     9132 non-null   float64
 7   Kp_Index  9132 non-null   int64
 8   Sunspots  9132 non-null   int64
dtypes: float64(4), int64(5)
memory usage: 642.2 KB

In [5]:
df.describe()

,Year,Day,Hour,B_Mag,Bz,Density,Speed,Kp_Index,Sunspots
count,9132.000000,9132.000000,9132.0,9132.000000,9132.000000,9132.000000,9132.000000,9132.000000,9132.000000
mean,2012.000000,183.140276,0.0,5.718703,-0.037615,11.366754,429.810994,17.719667,68.241459
std,7.212135,105.453110,0.0,2.568388,1.661152,72.708563,171.687331,11.035463,64.914270
min,2000.000000,1.000000,0.0,1.300000,-16.100000,0.100000,256.000000,0.000000,0.000000
25%,2006.000000,92.000000,0.0,4.000000,-0.800000,3.300000,356.000000,10.000000,13.000000
50%,2012.000000,183.000000,0.0,5.200000,0.000000,5.100000,406.000000,17.000000,51.000000
75%,2018.000000,274.000000,0.0,6.800000,0.700000,7.800000,481.000000,23.000000,111.000000
max,2024.000000,366.000000,0.0,33.400000,13.600000,999.900000,9999.000000,83.000000,353.000000

In [6]:
df = df.replace([999, 999.9, 99.9, 9999], np.nan)

In [7]:
df.describe()

,Year,Day,Hour,B_Mag,Bz,Density,Speed,Kp_Index,Sunspots
count,9132.000000,9132.000000,9132.0,9132.000000,9132.000000,9083.000000,9130.000000,9132.000000,9132.000000
mean,2012.000000,183.140276,0.0,5.718703,-0.037615,6.033921,427.714786,17.719667,68.241459
std,7.212135,105.453110,0.0,2.568388,1.661152,3.788320,97.043269,11.035463,64.914270
min,2000.000000,1.000000,0.0,1.300000,-16.100000,0.100000,256.000000,0.000000,0.000000
25%,2006.000000,92.000000,0.0,4.000000,-0.800000,3.300000,356.000000,10.000000,13.000000
50%,2012.000000,183.000000,0.0,5.200000,0.000000,5.000000,406.000000,17.000000,51.000000
75%,2018.000000,274.000000,0.0,6.800000,0.700000,7.700000,481.000000,23.000000,111.000000
max,2024.000000,366.000000,0.0,33.400000,13.600000,42.300000,1003.000000,83.000000,353.000000

In [8]:
df['Date'] = pd.to_datetime(df['Year'].astype(str) + df['Day'].astype(str), format='%Y%j')

In [9]:
df['Kp_Index'] = df['Kp_Index'] / 10.0

In [10]:
df.head(10)

   Year  Day  Hour  B_Mag   Bz  Density  Speed  Kp_Index  Sunspots       Date
0  2000    1     0    6.5 -0.0      2.0  721.0       4.0        71 2000-01-01
1  2000    2     0    5.1  0.4      2.0  679.0       3.0        75 2000-01-02
2  2000    3     0    4.9 -0.1      2.3  588.0       2.7        80 2000-01-03
3  2000    4     0    5.8 -0.6      2.3  577.0       2.7        95 2000-01-04
4  2000    5     0    6.0 -1.6      2.3  521.0       3.3       108 2000-01-05
5  2000    6     0    6.9 -0.0      4.0  533.0       3.3       126 2000-01-06
6  2000    7     0    4.5 -0.1      2.5  522.0       2.3       126 2000-01-07
7  2000    8     0    3.8  0.1      2.3  439.0       1.3       111 2000-01-08
8  2000    9     0    3.6  0.0      5.3  357.0       0.7       112 2000-01-09
9  2000   10     0    6.8 -1.0     11.2  334.0       1.7        96 2000-01-10

In [11]:
df[['Speed', 'Kp_Index', 'Sunspots', 'Bz']].corr()

             Speed  Kp_Index  Sunspots        Bz
Speed     1.000000  0.669187  0.068342 -0.012952
Kp_Index  0.669187  1.000000  0.237544 -0.353044
Sunspots  0.068342  0.237544  1.000000  0.007293
Bz       -0.012952 -0.353044  0.007293  1.000000

In [12]:
final_df = df[['Date', 'Speed', 'Density', 'Kp_Index', 'Sunspots', 'Bz']]
final_df.to_csv('solarstorm_clean.csv', index=False)